apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: shalmcharts.kramerul.github.com
spec:
  group: kramerul.github.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    plural: shalmcharts
    singular: shalmchart
    kind: ShalmChart
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            values:
              type: object
              additionalProperties: true
            kubeconfig:
              type: string
            url:
              type: string
            namespace:
              type: string
            args:
              type: array
            kwargs:
              type: object
