---
apiVersion: v1
kind: Secret
metadata:
  name: {{ call .Methods.secret_name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{.Values.name}}
  password: {{.Values.mariadb.image.tag}}
